name: githubaction_Describe_EC2Resource.yaml
permissions:
  id-token: write
  contents: write
  pull-requests: write
on: 
  push:
    branches:
      - main
env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: describe-ec2-resource	

jobs:
  aws_change_resource_tag_job:
    strategy:
      max-parallel: 1
      matrix:
        environment: ["describe-ec2-resource"]
    runs-on: ubuntu-22.04
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login-ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Debug file structure
        run: |
          ls -l
          ls -l ./Describe_Resource


      # - name: Build and Push
      #   id: docker_build
      #   uses: docker/build-push-action@v1
      #   with:
      #     context: ./Describe_Resource
      #     file: ./Dockerfile
      #     platforms: linux/amd64
      #     push: true
      #     tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
      - name: Build and Push
        run: |
          ls -l
          docker build . --file ./Describe_Resource/Dockerfile --tag ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push the Docker image
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

